### PR TITLE
Update setup.sh

### PR DESCRIPTION
**Pull request by atharvamax**

### CODE REVIEW

**Comment by DroidDynamix-Raj** [comment]
I think this project is now dead, because @adi1090x was not even merging pull request nor any commit he had made since 3 years ago

**Comment by DroidDynamix-Raj** [comment]
He is not even helping in fixing issues

**Comment by DroidDynamix-Raj** [comment]
Today I installed desktop with his setup file and when I run desktop (openbox-session) i got many errors and themes are not applied properly

**Comment by DroidDynamix-Raj** [comment]
So I just gave up

**Comment by adi1090x** [comment]
Fixed All Issues.

**Pull request closed without merging**
